# Generated by Django 4.2.5 on 2024-06-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the slide', max_length=100)),
                ('image', models.ImageField(help_text='Upload the slide image', upload_to='slider_images/')),
                ('caption', models.CharField(help_text='Caption text for the slide', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the slide')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
