# Generated by Django 4.2.5 on 2024-06-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0002_sliderimage_delete_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
