# Generated by Django 4.2.5 on 2024-06-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0003_sliderimage_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='order',
        ),
    ]
