# Generated by Django 4.2.5 on 2024-06-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0004_alter_sliderimage_options_remove_sliderimage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='title',
        ),
    ]
