# Generated by Django 4.2.5 on 2024-06-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0005_remove_sliderimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='title',
            field=models.CharField(default='exit', help_text='Title of the slide', max_length=100),
            preserve_default=False,
        ),
    ]
