# Generated by Django 4.2.5 on 2024-06-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0008_rename_title_slide_caption_remove_slide_button_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/logo/images/')),
                ('school_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
