# Generated by Django 4.2.5 on 2024-06-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0010_school_info_ab'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school_info',
            name='phone',
            field=models.CharField(default='exit', max_length=12),
            preserve_default=False,
        ),
    ]
