# Generated by Django 4.2.5 on 2024-06-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0011_school_info_email_school_info_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_info',
            name='working_hours',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
