# Generated by Django 4.2.5 on 2024-06-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0012_school_info_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_info',
            name='f_logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/logo/images/'),
        ),
    ]
