# Generated by Django 4.2.5 on 2024-06-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0015_welcome_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome',
            name='signature',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
