# Generated by Django 4.2.5 on 2024-06-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0019_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
