# Generated by Django 4.2.5 on 2024-06-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0022_account_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_superuser',
        ),
    ]
