# Generated by Django 4.2.5 on 2024-06-20 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0023_remove_account_is_active_remove_account_is_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
